### ISSUE TITLE
Some assumptions don't hold on non-FHS distros

### ISSUE THREAD

**Issue by thblt** [mdgaziur/findex#1]
Hey,

I've tried to play a bit with Findex on NixOS (a non-FHS linux distribution), and hit two bugs:

 - `query.rs:13` hardcodes `/usr/share/applications/`, which doesn't exist on Nix/Guix. I'm not sure what's the portable way to find this path, I suspect it's something like enumerating `$XDG_DATA_DIRS`.
 - The program crashes when an icon is missing in the current theme. This is probably an issue with my config, but crashing seems a bit of an extreme reaction :) (and such finders often are used in minimal setups, so missing icons *will* happen.

Regards,

**Comment by mdgaziur** [comment]
Umm, need to check path finding. Does your theme has "application-other" icon?

**Comment by thblt** [comment]
Apparently not :) 

In all fairness I think it has to do with environment variables, but I'm too lazy to investigate. ? Icon themes can be *weird* :)

Here's a simple fix:

```
From 37ac006a3b4f48b7404f8b3849102e00c1d032b6 Mon Sep 17 00:00:00 2001
From: Thibault Polge <thibault@thb.lt>
Date: Sat, 6 Nov 2021 13:59:44 +0100
Subject: [PATCH] Don't crash on missing icon

---
 src/query.rs | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)

diff --git a/src/query.rs b/src/query.rs
index 122e143..6a484d6 100644
--- a/src/query.rs
+++ b/src/query.rs
@@ -1,5 +1,5 @@
 use crate::common::spawn_process;
-use gtk::gdk::gdk_pixbuf::Pixbuf;
+use gtk::gdk::gdk_pixbuf::{Colorspace,Pixbuf};
 use gtk::gdk::EventKey;
 use gtk::prelude::*;
 use gtk::{
@@ -10,7 +10,7 @@ use std::process::exit;
 
 pub fn init_query() -> Entry {
     let query_box = Entry::builder().name("findex-query").build();
-    let mut desktop_entries = get_entries("/usr/share/applications");
+    let mut desktop_entries = get_entries("/home/thblt/.local/share/applications");
     desktop_entries.extend(get_entries(
         shellexpand::tilde("~/.local/share/applications").as_ref(),
     ));
@@ -181,10 +181,10 @@ fn get_icon(icon_name: &str) -> Pixbuf {
                 32,
                 IconLookupFlags::FORCE_SIZE | IconLookupFlags::USE_BUILTIN,
             )
+            .or::<Result<Pixbuf,()>>(Ok(Pixbuf::new(Colorspace::Rgb, false, 8, 32, 32)))
             .unwrap()
             .unwrap();
     }
-
     icon
 }
 
-- 
2.33.1

```

**Comment by thblt** [comment]
Erm don't fully apply the patch the first delta hardcodes a path under my $HOME instead of `/usr/share/applications`. It's the second that fixes the icon thing :) Sorry I went too fast.

**Comment by thblt** [comment]
Here's the correct patch:

```
From 3a227e9fd3b9c275baa24dc8220800e9bc9765a4 Mon Sep 17 00:00:00 2001
From: Thibault Polge <thibault@thb.lt>
Date: Sat, 6 Nov 2021 14:03:04 +0100
Subject: [PATCH] Don't crash on missing icon

---
 src/query.rs | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/src/query.rs b/src/query.rs
index 122e143..e16ed39 100644
--- a/src/query.rs
+++ b/src/query.rs
@@ -1,5 +1,5 @@
 use crate::common::spawn_process;
-use gtk::gdk::gdk_pixbuf::Pixbuf;
+use gtk::gdk::gdk_pixbuf::{Colorspace,Pixbuf};
 use gtk::gdk::EventKey;
 use gtk::prelude::*;
 use gtk::{
@@ -181,6 +181,7 @@ fn get_icon(icon_name: &str) -> Pixbuf {
                 32,
                 IconLookupFlags::FORCE_SIZE | IconLookupFlags::USE_BUILTIN,
             )
+            .or::<Result<Pixbuf,()>>(Ok(Pixbuf::new(Colorspace::Rgb, false, 8, 32, 32)))
             .unwrap()
             .unwrap();
     }
-- 
2.33.1
```

**Comment by mdgaziur** [comment]
umm, desktop entries does have desktop files from ~/.local/share/applications. Btw, how does the placeholder image looks like?

**Comment by thblt** [comment]
>_Btw, how does the placeholder image looks like?

With my patch, it's just an empty image, still better than a crash.  (Maybe you should set the second argument to `Pixbuf::new()` to true so it's fully transparent.)

**Comment by mdgaziur** [comment]
Can you make a pr?

**Comment by thblt** [comment]
Sure, give me a sec.

**Comment by MordragT** [comment]
I actually hit a similar issue on nixos because by default there exists no /usr/share/applications folder on nixos and also many applications dont show up on nixos because their data directory is like /nix/store/vfi1jn1xp8adq5g8acb4j9bpdfgdbfiw-gnome-terminal-3.42.0/share. I didnt investigate further but thought that maybe https://crates.io/crates/xdg would help to prevent both.

**Comment by thblt** [comment]
Indeed, this simple test does the job for me:

``` rust
fn main() {
    for p in xdg::BaseDirectories::new().unwrap().find_data_files("applications") {
        for f in std::fs::read_dir(p).unwrap() {
            println!("{}", f.unwrap().path().display());
        }
    }
}
```

**Comment by mdgaziur** [comment]
> I actually hit a similar issue on nixos because by default there exists no /usr/share/applications folder on nixos and also many applications dont show up on nixos because their data directory is like /nix/store/vfi1jn1xp8adq5g8acb4j9bpdfgdbfiw-gnome-terminal-3.42.0/share. I didnt investigate further but thought that maybe https://crates.io/crates/xdg would help to prevent both. If you want I could make a pr when I find time.

Sure! please make a PR
