### ISSUE TITLE
Tracking issue for fuzzy search

### ISSUE THREAD

**Issue by mdgaziur** [mdgaziur/findex#10]
Trying to add fuzzy search into this application. Currently I am trying to use [fuse-rust](https://github.com/blakeinstein/fuse-rust).

Trying with default values. Any suggestions for getting better results?

**Comment by mdgaziur** [comment]
Update: I'm planning to match with Exec too when using fuzzy search

**Comment by Blakeinstein** [comment]
I am actually tracking pain points in regards to `fuse-rust` can you tell me any specific problem you had with the package?

**Comment by mdgaziur** [comment]
I don't remember having any issues.
