### ISSUE TITLE
Display applications without writing

### ISSUE THREAD

**Issue by ams-hash** [mdgaziur/findex#14]
As you can see here. When no text is entered, no applications show up so there is only one column open
https://i.imgur.com/6Cei3FA.png

Now in this screenshot multiple columns of applications are here
https://i.imgur.com/VcrUpQz.png

The jump between one row and multiple and then back to one when finding your app is quite visually unappealing as the size rapidly changes as you type. There are currently maximum of 7 rows displayed at once. I think it would be better if you make it so 7 rows are always displayed even with nothing typed so theyre just placeholders so the size doesnt keep changing.

**Comment by mdgaziur** [comment]
Fixed on commit: 925023ed658453db80b6fc7d687155062ee52252
