### ISSUE TITLE
More themes by default

### ISSUE THREAD

**Issue by dumrich** [mdgaziur/findex#15]
**Is your feature request related to a problem? Please describe.**
I don't know if what I'm experiencing is a bug, but the findex with the default style.css doesn't look anything like the one in the README. 

**Describe the solution you'd like**
Add more themes to style Findex

**Comment by mdgaziur** [comment]
Screenshot?

**Comment by dumrich** [comment]
I reinstalled and it seems the problem is fixed

**Comment by mebesus** [comment]
Nevermind I do like the idea of having some custom themes. Will start working on it soon. Cheers!
