### ISSUE TITLE
settings.toml isn't working

### ISSUE THREAD

**Issue by RaafatTurki** [mdgaziur/findex#18]
`.config/findex/settings.toml` isn't auto generated and has no effect when manually created.
only `style.css` is generated when launching findex.

 - Distro: Arch
 - Version: 0.4.0.-1

**Comment by RaafatTurki** [comment]
installed the latest release and it works great, the `findex-bin` is a bit outdated apparently, closing.

**Comment by mdgaziur** [comment]
settings.toml isn't available in v0.4. It'll be released in v0.5

**Comment by mdgaziur** [comment]
If you want features from repo, use findex-git. Keep in mind that it's expected to break frequently when using findex-git.
