### ISSUE TITLE
Findex build failed error

### ISSUE THREAD

**Issue by coderDaiyan** [mdgaziur/findex#20]
Hello when i run the sh script i get this error
![image](https://user-images.githubusercontent.com/76746498/174588718-4818c494-c92b-43ed-951d-b471ec6bdde7.png)

what's the solution for this ?

TIA

**Comment by coderDaiyan** [comment]
I tried to install the `glib-2.0` package but it doesnt work

Im on fedora 36 / gnome 42

and 1 more thing I often face this error when I try to build something with cargo

**Comment by mdgaziur** [comment]
~Try to locate where glib-2.0.pc is located and add that directory to "PKG_CONFIG_PATH"~

Try this: ` sudo apt-get install libgtk-3-dev`

**Comment by coderDaiyan** [comment]
Thanks, It worked perfectly
