### ISSUE TITLE
Automatically resize window when number of options is smaller than min_score

### ISSUE THREAD

**Issue by qazip** [mdgaziur/findex#25]
When the number of options is smaller than min_score, the window should be resized to accomodate only the number of options.

Example:

Say your min_score is set to 5. If you search for "firefox" and it only shows 1 entry, then the window size should be such that only that entry fits. As it is, the window retains the size for the 5 entries.

**Comment by mdgaziur** [comment]
The problem is that the default value for `min_content_height` is set to 400. Setting it to 0 should fix the issue. I'm gonna set the default value to 0 then. Good catch!

**Comment by qazip** [comment]
> The problem is that the default value for `min_content_height` is set to 400. Setting it to 0 should fix the issue. I'm gonna set the default value to 0 then. Good catch!

Yes, this fixes the issue. Should've tried something like that before opening the issue, my bad.. Thank you!
