### ISSUE TITLE
Impossible Compile findex

### ISSUE THREAD

**Issue by dacorsa** [mdgaziur/findex#30]
Hi all
i'm have always compiled findex successfully but now i see   this error with the latest code downloaded from github:

   Compiling atk-sys v0.15.1
   Compiling pango-sys v0.15.10
   Compiling gtk-sys v0.15.3
   Compiling glib v0.15.12
   Compiling findex-plugin v0.1.0 (/app/findex/crates/findex-plugin)
   Compiling cairo-rs v0.15.12
   Compiling pango v0.15.10
   Compiling atk v0.15.1
   Compiling gdk-pixbuf v0.15.11
   Compiling gdk v0.15.4
   Compiling findex v0.6.0 (/app/findex/crates/findex)
error[E0658]: `let...else` statements are unstable
  --> crates/findex/src/gui/result_list_row.rs:95:5
   |
95 | /     let Some(cmd) = split(unsafe { row.data::<String>("app-cmd").unwrap().as_ref() }) else {
96 | |         show_dialog("Error", "Failed to launch application", MessageType::Error);
97 | |         return;
98 | |     };
   | |______^
   |
   = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `findex` due to previous error

How can i solve?
Thanks 
best regards

**Comment by mdgaziur** [comment]
Ahh, forgot to update minimum supported rustc version. Please update your rust compiler and let me know whether that fixes your problem.

**Comment by dacorsa** [comment]
update to rust 1.66 latest stable but for me there is always an error:

  Downloaded futures-task v0.3.25
  Downloaded crossbeam-utils v0.8.14
  Downloaded serde_derive v1.0.151
  Downloaded generational-arena v0.2.8
  Downloaded as_derive_utils v0.11.0
  Downloaded pest v2.5.1
  Downloaded serde_json v1.0.90
  Downloaded mio v0.8.5
  Downloaded cfg-expr v0.11.0
  Downloaded boxfnonce v0.1.1
  Downloaded anyhow v1.0.67
  Downloaded aho-corasick v0.7.20
  Downloaded serde v1.0.151
  Downloaded shlex v1.1.0
  Downloaded pkg-config v0.3.26
  Downloaded 66 crates (4.8 MB) in 0.77s
error: failed to open: /app/findex/target/release/.cargo-lock

Caused by:
  Permission denied (os error 13)
Copying files...

Installation done!
Now add "findex-daemon" to autostart. You may follow your desktop environment's guide to do this.
I'm starting "findex-daemon" for now.
[ERROR] Findex is already running with pid: 770508
[ERROR] Help: You may want to kill with `killall findex findex-daemon`
Findex can't bind hotkey in wayland.
To bind hotkey, bind the following command to your desired hotkey in the desktop environment you are using
echo 1 > ~/.config/findex/toggle_file
If you had Findex 0.6.0 installed, you may want to remove findex services from systemd.


best regards

**Comment by mdgaziur** [comment]
Try to remove "target" directory. It seems like it was created by root. You
might use sudo to do this

**Comment by mdgaziur** [comment]
I think it's better to delete the current clone and clone Findex again.

**Comment by dacorsa** [comment]
ok works with manual installation, but in the automated installation says always cargo not found

**Comment by mdgaziur** [comment]
Did you clone Findex again? Are you using rustup?

**Comment by dacorsa** [comment]
yes delete dir run rustup and re-compile

**Comment by mdgaziur** [comment]
Can you give me the output?

**Comment by dacorsa** [comment]
ok i have removed sudo from the command sudo ./installer.sh and now works:

21:05:16 dacorsa@NanoKDE /home/dacorsa $ findexupdate.sh 
[sudo] password di dacorsa: 
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
Lettura informazioni sullo stato... Fatto   
libkeybinder-3.0-dev è già alla versione più recente (0.3.2-1.1).
0 aggiornati, 0 installati, 0 da rimuovere e 5 non aggiornati.
fatal: il percorso di destinazione 'findex' esiste già e non è una directory vuota.
HEAD ora si trova a 4efcf0d Merge branch 'development' into release
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Decompressione degli oggetti in corso: 100% (3/3), 1.43 KiB | 1.43 MiB/s, fatto.
Da https://github.com/mdgaziur/findex
   4efcf0d..3f415ae  development -> origin/development
Aggiornamento di 4efcf0d..3f415ae
Fast-forward
 INSTALLATION.md | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
Già aggiornato.
make: ***  Nessuna regola per generare l'obiettivo «uninstall».  Arresto.
make: ***  Nessuna regola per generare l'obiettivo «clean».  Arresto.
Already found existing installation. Do you want to remove findex? [Y/N] Y
Removing files...
Removal done!
If you added "findex-daemon" to autostart, you may remove it now.
Install findex? [Y/N] Y
Installing Findex...
Building Findex...
    Finished release [optimized + debuginfo] target(s) in 0.08s
Copying files...

Installation done!
Now add "findex-daemon" to autostart. You may follow your desktop environment's guide to do this.
I'm starting "findex-daemon" for now.
Findex can't bind hotkey in wayland.
To bind hotkey, bind the following command to your desired hotkey in the desktop environment you are using
echo 1 > ~/.config/findex/toggle_file
If you had Findex 0.6.0 installed, you may want to remove findex services from systemd.
runuser: may not be used by non-root users
runuser: may not be used by non-root users
runuser: may not be used by non-root users
-rwxrwxr-x 2 dacorsa dacorsa 24405584 dic 25 20:06 /app/findex/target/release/findex
-rwxr-xr-x 1 root root 24405584 dic 25 21:06 /usr/bin/findex
21:06:16 dacorsa@NanoKDE /home/dacorsa $ 

and findexupdate.sh is:

sudo apt install libkeybinder-3.0-dev
cd /app
git clone https://github.com/mdgaziur/findex.git
cd /app/findex/
git reset --hard
git pull
git submodule update --init --recursive
git pull --recurse
make uninstall
make clean
./installer.sh
systemctl --user daemon-reload
runuser dacorsa -c "systemctl --user enable findex.service"
runuser dacorsa -c "systemctl --user enable findex-restarter.path"
runuser dacorsa -c "systemctl --user restart findex.service"
systemctl --user daemon-reload
ls -la /app/findex/target/release/findex
ls -la /usr/bin/findex
exit 0

**Comment by dacorsa** [comment]
ok i have removed sudo from the command sudo ./installer.sh and now works:

21:05:16 dacorsa@NanoKDE /home/dacorsa $ findexupdate.sh 
[sudo] password di dacorsa: 
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze... Fatto
Lettura informazioni sullo stato... Fatto   
libkeybinder-3.0-dev è già alla versione più recente (0.3.2-1.1).
0 aggiornati, 0 installati, 0 da rimuovere e 5 non aggiornati.
fatal: il percorso di destinazione 'findex' esiste già e non è una directory vuota.
HEAD ora si trova a 4efcf0d Merge branch 'development' into release
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Decompressione degli oggetti in corso: 100% (3/3), 1.43 KiB | 1.43 MiB/s, fatto.
Da https://github.com/mdgaziur/findex
   4efcf0d..3f415ae  development -> origin/development
Aggiornamento di 4efcf0d..3f415ae
Fast-forward
 INSTALLATION.md | 6 +++---
 1 file changed, 3 insertions(+), 3 deletions(-)
Già aggiornato.
make: ***  Nessuna regola per generare l'obiettivo «uninstall».  Arresto.
make: ***  Nessuna regola per generare l'obiettivo «clean».  Arresto.
Already found existing installation. Do you want to remove findex? [Y/N] Y
Removing files...
Removal done!
If you added "findex-daemon" to autostart, you may remove it now.
Install findex? [Y/N] Y
Installing Findex...
Building Findex...
    Finished release [optimized + debuginfo] target(s) in 0.08s
Copying files...

Installation done!
Now add "findex-daemon" to autostart. You may follow your desktop environment's guide to do this.
I'm starting "findex-daemon" for now.
Findex can't bind hotkey in wayland.
To bind hotkey, bind the following command to your desired hotkey in the desktop environment you are using
echo 1 > ~/.config/findex/toggle_file
If you had Findex 0.6.0 installed, you may want to remove findex services from systemd.
runuser: may not be used by non-root users
runuser: may not be used by non-root users
runuser: may not be used by non-root users
-rwxrwxr-x 2 dacorsa dacorsa 24405584 dic 25 20:06 /app/findex/target/release/findex
-rwxr-xr-x 1 root root 24405584 dic 25 21:06 /usr/bin/findex
21:06:16 dacorsa@NanoKDE /home/dacorsa $ 

and findexupdate.sh is:

sudo apt install libkeybinder-3.0-dev
cd /app
git clone https://github.com/mdgaziur/findex.git
cd /app/findex/
git reset --hard
git pull
git submodule update --init --recursive
git pull --recurse
make uninstall
make clean
./installer.sh
systemctl --user daemon-reload
runuser dacorsa -c "systemctl --user enable findex.service"
runuser dacorsa -c "systemctl --user enable findex-restarter.path"
runuser dacorsa -c "systemctl --user restart findex.service"
systemctl --user daemon-reload
ls -la /app/findex/target/release/findex
ls -la /usr/bin/findex
exit 0

best regards

**Comment by mdgaziur** [comment]
That's how it was meant to be run. Should I close the issue?

**Comment by dacorsa** [comment]
Yes, you're a gentleman! :)
