### ISSUE TITLE
[Bug] `ParseIntError` in `getpid`.

### ISSUE THREAD

**Issue by monomycelium** [mdgaziur/findex#45]
When I run `findex-daemon` even though there are a few instances of `findex` running, I get the following error:
```
thread 'main' panicked at crates/findex-daemon/src/main.rs:32:28:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After digging in, I realised that the `pidof` command uses a space to separate multiple PIDs by default (see [man](https://manpages.ubuntu.com/manpages/jammy/en/man8/pidof.8.html)), while `getpid` splits the output using newline bytes. A simple solution is to split using spaces:
``` diff
--- crates/findex-daemon/src/main.rs.old        2023-10-29 15:20:31.918921390 +0800
+++ crates/findex-daemon/src/main.rs    2023-10-29 15:20:38.391694935 +0800
@@ -24 +24 @@
-        .split('\n')
+        .split(' ')
```

However, this feels like a naive way as not all Linux systems have `procps-ng` out of the box. Instead, you could use the [`processes_by_name`](https://docs.rs/sysinfo/latest/sysinfo/trait.SystemExt.html#method.processes_by_name) method of the [`sysinfo`](https://crates.io/crates/sysinfo) crate. Of course, that comes at the expense of the binary size. (But this is Rust after all, right?)

Of course, the simpler way would be to store the PIDs in the filesystem (like in `/var/run`). This way, we would not have to execute syscalls repeatedly. When the process exits, the PID can be removed from the store. (If that is too hard to implement, you could simple use `kill(2)` with a 0 signal to check if there a process with that PID is running.)

### References
- [Find PID of a Process by Name without Using popen() or system()](https://stackoverflow.com/a/891381)
- [Check if process exists given its pid](https://stackoverflow.com/a/9153003)
- [Get external process ID by name](https://stackoverflow.com/a/70283392)

**Comment by mdgaziur** [comment]
Hi there! Thanks for reporting this issue. I'm looking into this.

**Comment by monomycelium** [comment]
Thank you for accepting my suggestion. The latest commit has solved the issue for me.

**Comment by mdgaziur** [comment]
You're welcome 😃
