### ISSUE TITLE
Panics when there is a file without extension in `~/.local/share/applications`

### ISSUE THREAD

**Issue by murlakatamenka** [mdgaziur/findex#5]
Reason is here:

https://github.com/mdgaziur/findex/blob/e19403b3d31a75d7580c1f953dd8e6cb1225c2e9/src/query.rs#L132-L134

(unwrapping empty extension)

I'd suggest using something like `walkdir` or `jwalk` for easy iteration over looked for `.desktop ` entries.

Quick fix can be (checked with Rust 1.56):
```rust
        if app_path.extension().unwrap_or_default() != "desktop" {
            continue;
        }
```

(sorry, too late right now to make a PR)

**Comment by mdgaziur** [comment]
Ok I'll check

**Comment by harisahmed05** [comment]
Just did the quick fix. Thanks for mentioning `walkdir` or `jwalk`.
