### ISSUE TITLE
make highlight color customizable

### ISSUE THREAD

**Issue by geogiraux** [mdgaziur/findex#65]
## Is your feature request related to a problem? Please describe.
Everything seems customizable through css, except the highlighting color used for showing the matching request : it's currently orange.

## Describe the solution you'd like
a specif CSS class like "highlighted" making possible to change color or background for instance. but i guess a few properties might mess the app

## Describe alternatives you've considered
none I can found

**Comment by mdgaziur** [comment]
You can customise that via settings.toml. Check readme for more information.

**Comment by geogiraux** [comment]
oups, my bad ! thanks for your quick answer, I thought every UX related item was in style.css
why not put a special class for this span element, in order to use the custom/named colors defined in the css file ?

**Comment by mdgaziur** [comment]
Good suggestion, will add this in the next release.
