### ISSUE TITLE
[Bug] No search icon after installing

### ISSUE THREAD

**Issue by gsouf** [mdgaziur/findex#68]
## Description

Findex shows an error icon instead of the search icon as showcased in the readme.

## Do you already have Findex Installed? (If yes, how did you install?)

using `installer.sh`

## To Reproduce

Just installed the app as per the instructions and ran it

## Screenshots

![image](https://github.com/user-attachments/assets/e98b2510-1dba-4cf9-8c88-6de45e046526)

## System information
 - Distro: Fedora 40 spin XFCE
 - Findex Version:  commit `c6baf7a83f2b774e32ef0247b439bf79d5278c18` 

## Output of `rustc --version --verbose` (if you compiled findex on your machine):
```
rustc 1.81.0 (eeb90cda1 2024-09-04) (Fedora 1.81.0-4.fc40)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-unknown-linux-gnu
release: 1.81.0
LLVM version: 18.1.8
```

## Log/Output (if applicable)

Nothing special in the logs

```
$ findex
[INFO] Starting Findex...
[INFO] listening for hotkey...
```

## Additional context

Just installed findex as per the instruction, and started it, haven't done anything else special 

thanks

**Comment by mdgaziur** [comment]
This is happening probably because the icon "search" is not available on your system. Change the value of "entry_icon" in settings.toml to something else and try again.

**Comment by gsouf** [comment]
@mdgaziur you are right! I used an icon theme that apparently does not have a search icon available. Sorry for the inconvenience 

Thanks
