### ISSUE TITLE
Match on 'exec' for finding applications

### ISSUE THREAD

**Issue by stoerdebegga** [mdgaziur/findex#8]
I came across the project by coincidence and after testing I noticed something that was bugging me a bit. I was trying to find ```GIMP``` but there weren't any results, which is because you only match on the name from the ```.desktop``` file.

On Fedora - and presumably other Distributions as well - the name for ```GIMP``` is **GNU Image Manipulation Program** which explains the empty results list.

**Comment by mdgaziur** [comment]
This issue happens due to using regex pattern that matches if the name starts with given query. I'm trying to add fuzzy search to it. Gonna make a tracking issue for fuzzy search soon
